# Generated by Django 2.2.11 on 2020-06-02 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200531_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the City', max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.State')),
            ],
        ),
    ]
