# Generated by Django 2.2.11 on 2020-06-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_care_platform'),
        ('facility', '0012_auto_20200531_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.City'),
        ),
        migrations.AddField(
            model_name='testinglab',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.City'),
        ),
    ]
