# Generated by Django 2.2.11 on 2020-06-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0013_care_platform'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilityinfrastructure',
            unique_together={('facility', 'room_type', 'bed_type')},
        ),
    ]
