# Generated by Django 2.2.11 on 2020-05-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20200531_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
