# Generated by Django 2.2.11 on 2020-06-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_care_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfacility',
            name='admitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientfacility',
            name='discharged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsampletest',
            name='result',
            field=models.IntegerField(choices=[(1, 'Sample Sent'), (2, 'Report Pending'), (3, 'Positive'), (4, 'Negative'), (5, 'Presumptive Positive'), (6, 'Test Inconclusive')], default=1),
        ),
        migrations.AlterField(
            model_name='patienttransfer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Withdraw')], default=1),
        ),
    ]
