# Generated by Django 2.2.11 on 2020-06-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_patients'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientdisease',
            unique_together={('patient', 'disease')},
        ),
        migrations.AlterUniqueTogether(
            name='patientsymptom',
            unique_together={('patient', 'symptom')},
        ),
    ]
