# Generated by Django 2.2.11 on 2020-06-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_auto_20200606_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsampletest',
            name='date_of_sample',
            field=models.DateTimeField(verbose_name='date at which sample tested'),
        ),
    ]
